"""autogenerated by genpy from MD03ARM/Reg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Reg(genpy.Message):
  _md5sum = "bab797c531c022f53404b77dfb5a648a"
  _type = "MD03ARM/Reg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 B0_direction
int64 B0_speed
int64 B2_direction
int64 B2_speed
int64 B4_direction
int64 B4_speed
int64 B6_direction
int64 B6_speed

"""
  __slots__ = ['B0_direction','B0_speed','B2_direction','B2_speed','B4_direction','B4_speed','B6_direction','B6_speed']
  _slot_types = ['int64','int64','int64','int64','int64','int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       B0_direction,B0_speed,B2_direction,B2_speed,B4_direction,B4_speed,B6_direction,B6_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Reg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.B0_direction is None:
        self.B0_direction = 0
      if self.B0_speed is None:
        self.B0_speed = 0
      if self.B2_direction is None:
        self.B2_direction = 0
      if self.B2_speed is None:
        self.B2_speed = 0
      if self.B4_direction is None:
        self.B4_direction = 0
      if self.B4_speed is None:
        self.B4_speed = 0
      if self.B6_direction is None:
        self.B6_direction = 0
      if self.B6_speed is None:
        self.B6_speed = 0
    else:
      self.B0_direction = 0
      self.B0_speed = 0
      self.B2_direction = 0
      self.B2_speed = 0
      self.B4_direction = 0
      self.B4_speed = 0
      self.B6_direction = 0
      self.B6_speed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_8q.pack(_x.B0_direction, _x.B0_speed, _x.B2_direction, _x.B2_speed, _x.B4_direction, _x.B4_speed, _x.B6_direction, _x.B6_speed))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.B0_direction, _x.B0_speed, _x.B2_direction, _x.B2_speed, _x.B4_direction, _x.B4_speed, _x.B6_direction, _x.B6_speed,) = _struct_8q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_8q.pack(_x.B0_direction, _x.B0_speed, _x.B2_direction, _x.B2_speed, _x.B4_direction, _x.B4_speed, _x.B6_direction, _x.B6_speed))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.B0_direction, _x.B0_speed, _x.B2_direction, _x.B2_speed, _x.B4_direction, _x.B4_speed, _x.B6_direction, _x.B6_speed,) = _struct_8q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8q = struct.Struct("<8q")
