/* Auto-generated by genmsg_cpp for file /home/parallels/fuerte_workspace/STM32_USB/msg/Battery.msg */
#ifndef STM32_USB_MESSAGE_BATTERY_H
#define STM32_USB_MESSAGE_BATTERY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace STM32_USB
{
template <class ContainerAllocator>
struct Battery_ {
  typedef Battery_<ContainerAllocator> Type;

  Battery_()
  : battery(0)
  {
  }

  Battery_(const ContainerAllocator& _alloc)
  : battery(0)
  {
  }

  typedef int32_t _battery_type;
  int32_t battery;


  typedef boost::shared_ptr< ::STM32_USB::Battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::STM32_USB::Battery_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Battery
typedef  ::STM32_USB::Battery_<std::allocator<void> > Battery;

typedef boost::shared_ptr< ::STM32_USB::Battery> BatteryPtr;
typedef boost::shared_ptr< ::STM32_USB::Battery const> BatteryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::STM32_USB::Battery_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::STM32_USB::Battery_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace STM32_USB

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::STM32_USB::Battery_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::STM32_USB::Battery_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::STM32_USB::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "295e87f732e03ed6443766199f72b602";
  }

  static const char* value(const  ::STM32_USB::Battery_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x295e87f732e03ed6ULL;
  static const uint64_t static_value2 = 0x443766199f72b602ULL;
};

template<class ContainerAllocator>
struct DataType< ::STM32_USB::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "STM32_USB/Battery";
  }

  static const char* value(const  ::STM32_USB::Battery_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::STM32_USB::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 battery\n\
\n\
";
  }

  static const char* value(const  ::STM32_USB::Battery_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::STM32_USB::Battery_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::STM32_USB::Battery_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.battery);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Battery_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::STM32_USB::Battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::STM32_USB::Battery_<ContainerAllocator> & v) 
  {
    s << indent << "battery: ";
    Printer<int32_t>::stream(s, indent + "  ", v.battery);
  }
};


} // namespace message_operations
} // namespace ros

#endif // STM32_USB_MESSAGE_BATTERY_H

