/* Auto-generated by genmsg_cpp for file /home/santiago/fuerte_workspace/STM32_USB/msg/Compass.msg */
#ifndef STM32_USB_MESSAGE_COMPASS_H
#define STM32_USB_MESSAGE_COMPASS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace STM32_USB
{
template <class ContainerAllocator>
struct Compass_ {
  typedef Compass_<ContainerAllocator> Type;

  Compass_()
  : compass(0.0)
  {
  }

  Compass_(const ContainerAllocator& _alloc)
  : compass(0.0)
  {
  }

  typedef float _compass_type;
  float compass;


  typedef boost::shared_ptr< ::STM32_USB::Compass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::STM32_USB::Compass_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Compass
typedef  ::STM32_USB::Compass_<std::allocator<void> > Compass;

typedef boost::shared_ptr< ::STM32_USB::Compass> CompassPtr;
typedef boost::shared_ptr< ::STM32_USB::Compass const> CompassConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::STM32_USB::Compass_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::STM32_USB::Compass_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace STM32_USB

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::STM32_USB::Compass_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::STM32_USB::Compass_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::STM32_USB::Compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "071a7bf0338a5c920686d632df45950e";
  }

  static const char* value(const  ::STM32_USB::Compass_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x071a7bf0338a5c92ULL;
  static const uint64_t static_value2 = 0x0686d632df45950eULL;
};

template<class ContainerAllocator>
struct DataType< ::STM32_USB::Compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "STM32_USB/Compass";
  }

  static const char* value(const  ::STM32_USB::Compass_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::STM32_USB::Compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 compass\n\
\n\
";
  }

  static const char* value(const  ::STM32_USB::Compass_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::STM32_USB::Compass_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::STM32_USB::Compass_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.compass);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Compass_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::STM32_USB::Compass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::STM32_USB::Compass_<ContainerAllocator> & v) 
  {
    s << indent << "compass: ";
    Printer<float>::stream(s, indent + "  ", v.compass);
  }
};


} // namespace message_operations
} // namespace ros

#endif // STM32_USB_MESSAGE_COMPASS_H

