"""autogenerated by genpy from MD03ARIA/encoder.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class encoder(genpy.Message):
  _md5sum = "e4b10ca275ee312169b4dee797690312"
  _type = "MD03ARIA/encoder"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 rpulses
int8 rdirection
int8 lpulses
int8 ldirection



"""
  __slots__ = ['rpulses','rdirection','lpulses','ldirection']
  _slot_types = ['int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rpulses,rdirection,lpulses,ldirection

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(encoder, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.rpulses is None:
        self.rpulses = 0
      if self.rdirection is None:
        self.rdirection = 0
      if self.lpulses is None:
        self.lpulses = 0
      if self.ldirection is None:
        self.ldirection = 0
    else:
      self.rpulses = 0
      self.rdirection = 0
      self.lpulses = 0
      self.ldirection = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4b.pack(_x.rpulses, _x.rdirection, _x.lpulses, _x.ldirection))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.rpulses, _x.rdirection, _x.lpulses, _x.ldirection,) = _struct_4b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4b.pack(_x.rpulses, _x.rdirection, _x.lpulses, _x.ldirection))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.rpulses, _x.rdirection, _x.lpulses, _x.ldirection,) = _struct_4b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4b = struct.Struct("<4b")
