/* Auto-generated by genmsg_cpp for file /home/kauil/fuerte_workspace/MD03ARIA/msg/encoder.msg */
#ifndef MD03ARIA_MESSAGE_ENCODER_H
#define MD03ARIA_MESSAGE_ENCODER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace MD03ARIA
{
template <class ContainerAllocator>
struct encoder_ {
  typedef encoder_<ContainerAllocator> Type;

  encoder_()
  : rpulses(0)
  , rdirection(0)
  , lpulses(0)
  , ldirection(0)
  {
  }

  encoder_(const ContainerAllocator& _alloc)
  : rpulses(0)
  , rdirection(0)
  , lpulses(0)
  , ldirection(0)
  {
  }

  typedef int8_t _rpulses_type;
  int8_t rpulses;

  typedef int8_t _rdirection_type;
  int8_t rdirection;

  typedef int8_t _lpulses_type;
  int8_t lpulses;

  typedef int8_t _ldirection_type;
  int8_t ldirection;


  typedef boost::shared_ptr< ::MD03ARIA::encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::MD03ARIA::encoder_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct encoder
typedef  ::MD03ARIA::encoder_<std::allocator<void> > encoder;

typedef boost::shared_ptr< ::MD03ARIA::encoder> encoderPtr;
typedef boost::shared_ptr< ::MD03ARIA::encoder const> encoderConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::MD03ARIA::encoder_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::MD03ARIA::encoder_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace MD03ARIA

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::MD03ARIA::encoder_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::MD03ARIA::encoder_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::MD03ARIA::encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e4b10ca275ee312169b4dee797690312";
  }

  static const char* value(const  ::MD03ARIA::encoder_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe4b10ca275ee3121ULL;
  static const uint64_t static_value2 = 0x69b4dee797690312ULL;
};

template<class ContainerAllocator>
struct DataType< ::MD03ARIA::encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "MD03ARIA/encoder";
  }

  static const char* value(const  ::MD03ARIA::encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::MD03ARIA::encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 rpulses\n\
int8 rdirection\n\
int8 lpulses\n\
int8 ldirection\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::MD03ARIA::encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::MD03ARIA::encoder_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::MD03ARIA::encoder_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.rpulses);
    stream.next(m.rdirection);
    stream.next(m.lpulses);
    stream.next(m.ldirection);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct encoder_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::MD03ARIA::encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::MD03ARIA::encoder_<ContainerAllocator> & v) 
  {
    s << indent << "rpulses: ";
    Printer<int8_t>::stream(s, indent + "  ", v.rpulses);
    s << indent << "rdirection: ";
    Printer<int8_t>::stream(s, indent + "  ", v.rdirection);
    s << indent << "lpulses: ";
    Printer<int8_t>::stream(s, indent + "  ", v.lpulses);
    s << indent << "ldirection: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ldirection);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MD03ARIA_MESSAGE_ENCODER_H

